version: "3.9"

services:

  unbound-mailcow:
    image: ghcr.io/mailcow/unbound:1.24
    environment:
      - TZ=${TZ}
      - SKIP_UNBOUND_HEALTHCHECK=${SKIP_UNBOUND_HEALTHCHECK:-n}
    volumes:
      - ./data/hooks/unbound:/hooks
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
    restart: always
    tty: true
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.254
        aliases:
          - unbound

  mysql-mailcow:
    image: mariadb:10.11
    depends_on:
      - unbound-mailcow
    stop_grace_period: 45s
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      mailcow-network:
        aliases:
          - mysql

  redis-mailcow:
    image: redis:7.4.2-alpine
    entrypoint: ["/bin/sh","/redis-conf.sh"]
    volumes:
      - redis-vol-1:/data/
      - ./data/conf/redis/redis-conf.sh:/redis-conf.sh
    restart: always
    environment:
      - TZ=${TZ}
      - REDISPASS=${REDISPASS}
      - REDISMASTERPASS=${REDISMASTERPASS:-}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.249
        aliases:
          - redis

  clamd-mailcow:
    image: ghcr.io/mailcow/clamd:1.70
    restart: always
    depends_on:
      unbound-mailcow:
        condition: service_healthy
    dns:
      - 172.22.1.254
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/
      - clamd-db-vol-1:/var/lib/clamav
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: ghcr.io/mailcow/rspamd:2.2
    stop_grace_period: 30s
    depends_on:
      - dovecot-mailcow
      - clamd-mailcow
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=172.22.1
      - IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    volumes:
      - ./data/hooks/rspamd:/hooks
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        aliases:
          - rspamd

  # (other services follow the same corrected pattern…)
  # Dovecot/Postfix no longer bind host ports; only nginx-mailcow does.

  nginx-mailcow:
    image: ghcr.io/mailcow/nginx:1.03
    depends_on:
      - redis-mailcow
      - php-fpm-mailcow
      - sogo-mailcow
      - rspamd-mailcow
    environment:
      - TZ=${TZ}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    volumes:
      - ./data/web:/web:ro
      - ./data/assets/ssl/:/etc/ssl/mail/:ro
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    restart: always
    networks:
      mailcow-network:
        aliases:
          - nginx
      documents_lan:
        ipv4_address: 10.10.128.16
        mac_address: 02:42:0a:0a:80:16

  acme-mailcow:
    image: ghcr.io/mailcow/acme:1.93
    depends_on:
      - nginx-mailcow
      - unbound-mailcow
    dns:
      - 172.22.1.254
    environment:
      - TZ=${TZ}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - AUTODISCOVER_SAN=${AUTODISCOVER_SAN:-y}
      - DIRECTORY_URL=${DIRECTORY_URL:-}
      - ENABLE_SSL_SNI=${ENABLE_SSL_SNI:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
      - ONLY_MAILCOW_HOSTNAME=${ONLY_MAILCOW_HOSTNAME:-n}
      - LE_STAGING=${LE_STAGING:-n}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    volumes:
      - ./data/web/.well-known/acme-challenge:/var/www/acme
      - ./data/assets/ssl:/var/lib/acme/
      - ./data/assets/ssl-example:/var/lib/ssl-example/:ro
      - mysql-socket-vol-1:/var/run/mysqld/
    restart: always
    networks:
      mailcow-network:
        aliases:
          - acme

  netfilter-mailcow:
    image: ghcr.io/mailcow/netfilter:1.61
    stop_grace_period: 30s
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=172.22.1
      - IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
      - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-n}
      - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-n}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    volumes:
      - /lib/modules:/lib/modules:ro

  ipv6nat-mailcow:
    image: robbertkl/ipv6nat
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

# ===============================
# Networks
# ===============================
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mailcow
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
        - subnet: fd4d:6169:6c63:6f77::/64

  documents_lan:
    external: true

# ===============================
# Volumes
# ===============================
volumes:
  vmail-vol-1:
  vmail-index-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  postfix-vol-1:
  crypt-vol-1:
  sogo-web-vol-1:
  sogo-userdata-backup-vol-1:
  clamd-db-vol-1:
