version: "3.9"

services:

  unbound-mailcow:
    image: ghcr.io/mailcow/unbound:1.24
    environment:
      - TZ=${TZ}
      - SKIP_UNBOUND_HEALTHCHECK=${SKIP_UNBOUND_HEALTHCHECK:-n}
    volumes:
      - ./data/hooks/unbound:/hooks
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
    restart: always
    tty: true
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.254
        aliases:
          - unbound

  mysql-mailcow:
    image: mariadb:10.11
    depends_on:
      - unbound-mailcow
      - netfilter-mailcow
    stop_grace_period: 45s
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      mailcow-network:
        aliases:
          - mysql

  redis-mailcow:
    image: redis:7.4.2-alpine
    entrypoint: ["/bin/sh","/redis-conf.sh"]
    volumes:
      - redis-vol-1:/data/
      - ./data/conf/redis/redis-conf.sh:/redis-conf.sh
    restart: always
    depends_on:
      - netfilter-mailcow
    ports:
      - "${REDIS_PORT:-127.0.0.1:7654}:6379"
    environment:
      - TZ=${TZ}
      - REDISPASS=${REDISPASS}
      - REDISMASTERPASS=${REDISMASTERPASS:-}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mailcow-network:
        ipv4_address: 172.22.1.249
        aliases:
          - redis

  clamd-mailcow:
    image: ghcr.io/mailcow/clamd:1.70
    restart: always
    depends_on:
      unbound-mailcow:
        condition: service_healthy
    dns:
      - 172.22.1.254
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/
      - clamd-db-vol-1:/var/lib/clamav
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: ghcr.io/mailcow/rspamd:2.2
    stop_grace_period: 30s
    depends_on:
      - dovecot-mailcow
      - clamd-mailcow
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=172.22.1
      - IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    volumes:
      - ./data/hooks/rspamd:/hooks
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - 172.22.1.254
    networks:
      mailcow-network:
        aliases:
          - rspamd

  php-fpm-mailcow:
    image: ghcr.io/mailcow/phpfpm:1.93
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis-mailcow
    volumes:
      - ./data/hooks/phpfpm:/hooks
      - ./data/web:/web
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro
      - ./data/conf/rspamd/custom/:/rspamd_custom_maps
      - ./data/conf/dovecot/auth/mailcowauth.php:/mailcowauth/mailcowauth.php
      - ./data/web/inc/functions.inc.php:/mailcowauth/functions.inc.php
      - ./data/web/inc/functions.auth.inc.php:/mailcowauth/functions.auth.inc.php
      - ./data/web/inc/sessions.inc.php:/mailcowauth/sessions.inc.php
      - ./data/web/inc/functions.mailbox.inc.php:/mailcowauth/functions.mailbox.inc.php
      - ./data/web/inc/functions.ratelimit.inc.php:/mailcowauth/functions.ratelimit.inc.php
      - ./data/web/inc/functions.acl.inc.php:/mailcowauth/functions.acl.inc.php
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/sogo/:/etc/sogo/
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
      - ./data/conf/phpfpm/crons:/crons
      - ./data/conf/phpfpm/sogo-sso/:/etc/sogo-sso/
      - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf
      - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini
      - ./data/conf/dovecot/global_sieve_before:/global_sieve/before
      - ./data/conf/dovecot/global_sieve_after:/global_sieve/after
      - ./data/assets/templates:/tpls
      - ./data/conf/nginx/:/etc/nginx/conf.d/
    dns:
      - 172.22.1.254
    environment:
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-BLF-CRYPT}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
      - IPV4_NETWORK=172.22.1
      - IPV6_NETWORK=fd4d:6169:6c63:6f77::/64
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - SMTPS_PORT=${SMTPS_PORT:-465}
      - SMTP_PORT=${SMTP_PORT:-25}
      - API_KEY=${API_KEY:-invalid}
      - API_KEY_READ_ONLY=${API_KEY_READ_ONLY:-invalid}
      - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
      - SKIP_FTS=${SKIP_FTS:-y}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
      - SKIP_OLEFY=${SKIP_OLEFY:-n}
      - SKIP_SOGO=${SKIP_SOGO:-n}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MASTER=${MASTER:-y}
      - DEV_MODE=${DEV_MODE:-n}
      - DEMO_MODE=${DEMO_MODE:-n}
      - WEBAUTHN_ONLY_TRUSTED_VENDORS=${WEBAUTHN_ONLY_TRUSTED_VENDORS:-n}
      - CLUSTERMODE=${CLUSTERMODE:-}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.phpfpm_keycloak_sync.schedule: "@every 1m"
      ofelia.job-exec.phpfpm_keycloak_sync.no-overlap: "true"
      ofelia.job-exec.phpfpm_keycloak_sync.command: "/bin/bash -c \"php /crons/keycloak-sync.php || exit 0\""
      ofelia.job-exec.phpfpm_ldap_sync.schedule: "@every 1m"
      ofelia.job-exec.phpfpm_ldap_sync.no-overlap: "true"
      ofelia.job-exec.phpfpm_ldap_sync.command: "/bin/bash -c \"php /crons/ldap-sync.php || exit 0\""
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  # ... (all other services same pattern, fixed indentation, no duplicate host ports, static IPs written explicitly, no ":z"/":Z" labels)

  nginx-mailcow:
    image: ghcr.io/mailcow/nginx:1.03
    depends_on:
      - redis-mailcow
      - php-fpm-mailcow
      - sogo-mailcow
      - rspamd-mailcow
    environment:
      - TZ=${TZ}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    volumes:
      - ./data/web:/web:ro
      - ./data/assets/ssl/:/etc/ssl/mail/:ro
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
    restart: always
    networks:
      mailcow-network:
        aliases:
          - nginx
      documents_lan:
        ipv4_address: 10.10.128.16

  acme-mailcow:
    image: ghcr.io/mailcow/acme:1.93
    depends_on:
      - nginx-mailcow
      - unbound-mailcow
    dns:
      - 172.22.1.254
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - AUTODISCOVER_SAN=${AUTODISCOVER_SAN:-y}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
      - DIRECTORY_URL=${DIRECTORY_URL:-}
      - ENABLE_SSL_SNI=${ENABLE_SSL_SNI:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
      - ONLY_MAILCOW_HOSTNAME=${ONLY_MAILCOW_HOSTNAME:-n}
      - LE_STAGING=${LE_STAGING:-n}
      - TZ=${TZ}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
    volumes:
      - ./data/web/.well-known/acme-challenge:/var/www/acme
      - ./data/assets/ssl:/var/lib/acme/
      - ./data/assets/ssl-example:/var/lib/ssl-example/:ro
      - mysql-socket-vol-1:/var/run/mysqld/
    restart: always
    networks:
      mailcow-network:
        aliases:
          - acme

# ---------------------------
# Networks
# ---------------------------
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mailcow
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
        - subnet: fd4d:6169:6c63:6f77::/64

  documents_lan:
    external: true

# ---------------------------
# Volumes
# ---------------------------
volumes:
  vmail-vol-1:
  vmail-index-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  postfix-vol-1:
  crypt-vol-1:
  sogo-web-vol-1:
  sogo-userdata-backup-vol-1:
  clamd-db-vol-1:
